### ISSUE TITLE
Update runtime

### ISSUE THREAD

**Issue by Justinzobel** [flathub/de.ifw_dresden.nagstamon#9]
This is using an incredibly old and unsupported runtime. Please update ASAP.

**Comment by HenriWahl** [comment]
@Justinzobel please see https://github.com/flathub/de.ifw_dresden.nagstamon/pull/8#issuecomment-2027027520 and help testing.

**Comment by Justinzobel** [comment]
Ah, I saw the PR title and assumed it didn't have the runtime update, so I created the issue. Not a user of the software, just trying to get everyone on current supported runtimes for security.
